# Site settings
name: 邵胖胖爱学习
email: shaoyue1993@163.com
author: YueShao
url: YueShao.github.io
resume_site: YueShao.github.io
github: https://github.com/YueShao/
baseurl: ""
description: 我很爱学习哒，不信，你看我的鼻子都变长啦～
meta_description: 邵胖胖;个人博客;生而为吃
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: YueShao

# Build settings
markdown: kramdown

baidu_analysis: fb955d8c93381e2fc3e093d141628241

